sudo: required
services:
  - docker

before_install:
  - docker build -t ciobacs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ciobacs/react-test npm test 

after_success:
  - docker build -t ciobacs/multi-client ./client
  - docker build -t ciobacs/multi-nginx ./nginx
  - docker build -t ciobacs/multi-server ./server
  - docker build -t ciobacs/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push into hub
  - docker push ciobacs/multi-client
  - docker push ciobacs/multi-nginx
  - docker push ciobacs/multi-server
  - docker push ciobacs/multi-worker
